// Part of the APK.audio project — http://APK.audio — made by Anthony Kuzub
// MIT Licence. Free, for everyone, for ever. Full text in LICENSE at the root.
/**
 * Write the worked Flow drawing that the Big Picture narrative points at.
 *
 * A narrative that names a drawing needs a drawing to name, and the drawing has
 * to be a real one — produced by this app's own exporter, not drawn by hand in
 * a text editor to look like one. So the example is GENERATED, from a script
 * that is committed beside it: `npm run example` rebuilds it, and a change to
 * the entity model or the exporter shows up in the diff instead of quietly
 * making the committed file a fossil.
 *
 *     source ─▶ process ─▶ split ─┬─▶ sink
 *                                 └─▶ sink
 *
 * Four symbols, so the set is exercised rather than asserted; the split's two
 * outputs are what prove ports spread along one edge without special-casing.
 */
import { writeFileSync } from 'node:fs';
import type { PortRef } from '../src/core/types';
import { connectPorts, createSchematic, placeBlock } from '../src/flow/Schematic';
import { buildDxf } from '../src/io/exportDxf/buildDxf';
import { Doc } from '../src/model/Doc';

const model = createSchematic();
const source = placeBlock(model, 'flow.source', { x: -6, y: 0 }, '0', 'SRC1');
const process = placeBlock(model, 'flow.process', { x: -2, y: 0 }, '0', 'PROC1');
const split = placeBlock(model, 'flow.split', { x: 2, y: 0 }, '0', 'SPLIT1');
const sinkA = placeBlock(model, 'flow.sink', { x: 6, y: 1.5 }, '0', 'SINK_A');
const sinkB = placeBlock(model, 'flow.sink', { x: 6, y: -1.5 }, '0', 'SINK_B');
if (!source || !process || !split || !sinkA || !sinkB) throw new Error('catalogue changed');

const at = (id: number, portId: string): PortRef => ({ placementId: id, portId });
connectPorts(model, at(source.id, 'OUT'), at(process.id, 'IN'));
connectPorts(model, at(process.id, 'OUT'), at(split.id, 'IN'));
connectPorts(model, at(split.id, 'OUT_A'), at(sinkA.id, 'IN'));
connectPorts(model, at(split.id, 'OUT_B'), at(sinkB.id, 'IN'));

const target = '../Drawings/big-picture-flow';
writeFileSync(`${target}.dxf`, buildDxf(new Doc(), 'in', [], model));
writeFileSync(
  `${target}.json`,
  `${JSON.stringify(
    {
      note:
        'The schematic model behind big-picture-flow.dxf. Generated by ' +
        'APK:Softapps/DXF/Code/scripts/emitExampleDrawing.ts — npm run example.',
      placements: model.placements,
      connectors: model.connectors,
    },
    null,
    2,
  )}\n`,
);
console.log(
  `wrote ${target}.dxf — ${model.placements.length} placements, ${model.connectors.length} connectors`,
);
